#!/usr/bin/env python3
"""
Generate a fixed Train/Val/Test split manifest for ViSEC dataset.

This script creates a single source of truth for data splitting that all
training and evaluation scripts must read from, ensuring that every model
is compared on the exact same test set.

Split ratio: 80% Train / 10% Val / 10% Test (stratified by emotion label).
Random seed: 42 (fixed for reproducibility).

Output: split_manifest.json in the project root directory.
"""

import json
from pathlib import Path

from datasets import load_dataset
from sklearn.model_selection import train_test_split

RANDOM_STATE = 42
OUTPUT_PATH = Path(__file__).parent / "split_manifest.json"


def main():
    print("=" * 60)
    print("GENERATING FIXED SPLIT MANIFEST FOR ViSEC")
    print("=" * 60)

    # ------------------------------------------------------------------
    # 1. Load ViSEC dataset
    # ------------------------------------------------------------------
    print("\nLoading ViSEC dataset from HuggingFace...")
    dataset = load_dataset("hustep-lab/ViSEC", split="train", trust_remote_code=True)
    df = dataset.to_pandas()

    print(f"Total samples: {len(df)}")
    print(f"Columns: {df.columns.tolist()}")
    print(f"\nEmotion distribution:")
    print(df["emotion"].value_counts().to_string())
    print(f"\nSpeaker count: {df['speaker_id'].nunique()}")

    # ------------------------------------------------------------------
    # 2. Stratified split: 80% train, 10% val, 10% test
    # ------------------------------------------------------------------
    # First split: 80% train vs 20% remaining
    indices = list(range(len(df)))
    train_idx, remaining_idx = train_test_split(
        indices,
        test_size=0.2,
        random_state=RANDOM_STATE,
        stratify=df["emotion"].values,
    )

    # Second split: 50/50 on the remaining 20% → 10% val, 10% test
    remaining_emotions = df["emotion"].values[remaining_idx]
    val_idx, test_idx = train_test_split(
        remaining_idx,
        test_size=0.5,
        random_state=RANDOM_STATE,
        stratify=remaining_emotions,
    )

    print(f"\nSplit sizes:")
    print(f"  Train: {len(train_idx)} ({len(train_idx)/len(df)*100:.1f}%)")
    print(f"  Val:   {len(val_idx)} ({len(val_idx)/len(df)*100:.1f}%)")
    print(f"  Test:  {len(test_idx)} ({len(test_idx)/len(df)*100:.1f}%)")

    # ------------------------------------------------------------------
    # 3. Verify no overlap
    # ------------------------------------------------------------------
    train_set = set(train_idx)
    val_set = set(val_idx)
    test_set = set(test_idx)

    assert len(train_set & val_set) == 0, "Train/Val overlap detected!"
    assert len(train_set & test_set) == 0, "Train/Test overlap detected!"
    assert len(val_set & test_set) == 0, "Val/Test overlap detected!"
    assert len(train_set) + len(val_set) + len(test_set) == len(df), \
        "Split sizes don't add up!"
    print("\n✓ No overlap between splits. Integrity verified.")

    # ------------------------------------------------------------------
    # 4. Verify stratification
    # ------------------------------------------------------------------
    print("\nPer-split emotion distribution:")
    for name, idxs in [("Train", train_idx), ("Val", val_idx), ("Test", test_idx)]:
        dist = df.iloc[idxs]["emotion"].value_counts()
        total = len(idxs)
        print(f"  {name}:")
        for emotion, count in dist.items():
            print(f"    {emotion}: {count} ({count/total*100:.1f}%)")

    # ------------------------------------------------------------------
    # 5. Save manifest
    # ------------------------------------------------------------------
    manifest = {
        "description": (
            "Fixed Train/Val/Test split for ViSEC dataset. "
            "All training and evaluation scripts MUST read from this file. "
            "Generated by generate_splits.py."
        ),
        "dataset": "hustep-lab/ViSEC",
        "total_samples": len(df),
        "random_state": RANDOM_STATE,
        "split_ratio": "80/10/10",
        "stratify_by": "emotion",
        "train_indices": sorted(train_idx),
        "val_indices": sorted(val_idx),
        "test_indices": sorted(test_idx),
    }

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)

    print(f"\n✓ Manifest saved to: {OUTPUT_PATH}")
    print("=" * 60)


if __name__ == "__main__":
    main()
